### ISSUE TITLE
unmarshal unknown message

### ISSUE THREAD

**Issue by 89z** [CrowdStrike/csproto#40] opened 2022-05-15 15:57 UTC
Is it possible to Unmarshal an unknown message, given some arbitrary input bytes? Similar to `json.Unmarshal`

**Comment by dylan-bourque** [comment] 2022-05-16 02:06
Unfortunately, it's not possible in the general case. The encoded data isn't self describing so you have to have the additional metadata from either the .proto file or the struct tags on the generated Go types.

Theoretically, you could read an arbitrary message into a `map[int]interface{}`, keyed by the integer field tag, but that's not really very practical.  It's also problematic because the encoded representation of `string`, `bytes`, and nested messages are identical so you'd have to use some external metadata source to know field names, types, etc. for each field tag.

**Comment by 89z** [comment] 2022-05-23 16:51
You can differ string from byte slice [1], so then its just a matter of differing those from a Message. As you said, you cant get a perfect Unmarshal in every case, but you could have some function, where the user can make decisions on what to do. Such as:

- If value is type 2 and valid message, Unmarshal as message
- If value is type 2 and valid message, Unmarshal as bytes
- If value is type 2 and valid message, Unmarshal as string, if valid string

or something like that. I guess my point is, that even without a schema, a ProtoBuf message is not a total black box, and shouldn't be treated as such. We should have tools that can at least make an attempt to extract data within reason.


1. https://github.com/89z/format/blob/v1.35.3/format.go#L17-L35

**Comment by dylan-bourque** [comment] 2022-05-23 17:00
The problem is that there's no way to tell which one of those 3 things the bytes following that wire type value of 2 contains.  The encoded data is `tag|wire type|raw bytes`.  It's simple to read off the tag and wire type, but decoding the raw bytes following that requires knowing which one of those 3 types of data it contains.  You can always read it as `[]byte` because that's what it actually is.  But trying to read a string as a message (or vice versa) could fail.

If you have different source of the necessary metadata (like the data type for each tag value) then you're more than welcome to use the primitives on `Decoder` to write your own parser.  I'm not inclined to complicate this API to accommodate that edge case, though.

**Comment by 89z** [comment] 2022-05-23 17:02
I dont think its an edge case, as Google even supports it:

**Comment by dylan-bourque** [comment] 2022-05-23 17:45
From the docs for that method:
> Note that the protobuf wire format is not fully self-describing, so abductive inference may attempt to expand a bytes value as a message that is not actually a message. It is a best-effort guess.

As an example, say the first byte of the data is 0x42.  Is that a UTF-8 'B' that's the start of a string or is it an encoded message with a tag of 8 (`8 << 3 | 2 == 0x42`)?  You can't know that given only the binary data.

**Comment by dylan-bourque** [comment] 2022-05-23 17:59
As I called out in the project README, we're not looking to be a 100% replacement for all things Protobuf.  Our goal is to provide a minimal API that is runtime agnostic across Gogo and both version of Google.

I was able to find several references to `UnmarshalAbductive()` guessing wrong via a quick Google search which, tbh, makes me even less inclined to add it.

**Comment by 89z** [comment] 2022-05-23 18:03
I am quite familiar with the ProtoBuf specification, so I don't need you to point out pathological cases. If you have a value of wire type 2, then it can be a string, byte slice, or embedded message. I have shown how you can determine if a value is string or bytes, so its just a matter of determining if a value is a message.

As you said, you cant do this perfectly in all cases. However you can guess, or you can let the user decide what to do in these cases. Either way, I think making an attempt is better than just throwing hands up, and saying its not possible. You could parse some arbitrary bytes as a Message, then print that Message, along with an unparsed string representation of the same bytes. Then as a human, you could look at these two results, and make your own decision which representation is the correct one. Its not an ideal process, but that's the fault a flawed format (ProtoBuf), rather than a flaw in parsing.

**Comment by dylan-bourque** [comment] 2022-05-23 18:47
> its just a matter of determining if a value is a message.
What I'm saying is that this is problematic at best.  I don't feel like a first byte of 0x42 is pathological at all, that's just the first example I thought of.  Lots of strings start with 'B', lots of messages have a field with a tag of 8, and it's certainly not unreasonable for that to be the first byte of an arbitrary `[]byte`.

I'll gladly review a PR if you want to take a shot at an implementation that solves even that simple case, but I'll say again that I'm not particularly keen on adding an API that will likely result in a stream of "Doesn't work with [some message]" bug reports.  Both the documentation for that function and [this issue](https://github.com/golang/protobuf/issues/1370) from the V1 Protobuf API are pretty clear that it's based on heuristic logic that's assumed to be wrong some of the time.

> Then as a human, you could look at these two results, and make your own decision which representation is the correct one.
You can already use `protopack.UnmarshalAbductive()` to do this today.  What's the specific benefit of adding the same non-deterministic function to this library?

**Comment by 89z** [comment] 2022-05-23 19:09
> I don't feel like a first byte of 0x42 is pathological at all, that's just the first example I thought of. Lots of strings start with 'B', lots of messages have a field with a tag of 8, and it's certainly not unreasonable for that to be the first byte of an arbitrary `[]byte`.

The test of "is this a valid message", cannot simply be answered by looking only at the first byte. All the field numbers need to be valid [1], and any value need to pass ParseError as well. So if some arbitrary bytes pass all the tests of "is this a message", at that point it MIGHT be a message, in the absence of a schema.

> likely result in a stream of "Doesn't work with [some message]" bug reports. Both the documentation for that function and [this issue](https://github.com/golang/protobuf/issues/1370) from the V1 Protobuf API are pretty clear that it's based on heuristic logic that's assumed to be wrong some of the time.

I think youre exaggerating the problem. The issue you linked was posted by me (alternate account). So that's literally one issue in 12 years [3], hardly a stream.

> You can already use `protopack.UnmarshalAbductive()` to do this today. What's the specific benefit of adding the same non-deterministic function to this library?

The existing function, tried to parse bytes as an embedded message. If it passes (as I described above), then it just adds an embedded message without question. This could be improved by adding something like this:

~~~go
func Unmarshal(b []byte, useMessage bool) (Message, error)
~~~

then user can control what the result is. `true` or `false` will not be perfect for all inputs, but its an improvement over the existing function, which gives no choice at all.

1. https://google.golang.org/protobuf/encoding/protowire#Number
2. https://google.golang.org/protobuf/encoding/protowire#ParseError
3. https://github.com/golang/protobuf/commit/fceca43ab4ee265b65daf790ef1ec45cda796c87

**Comment by dylan-bourque** [comment] 2022-05-23 19:30
> The issue you linked was posted by me (alternate account).

No way for me to know that, though. 😉 

The signature of `Unmarshal([]byte, interface{}) error` is intentionally and specifically set up to mirror `proto.Unmarshal()` from all 3 underlying runtime implementations.  Changing that is unacceptable as it violates the primary reason this library exists, which is to be a shim between consumer code and the 3 runtimes.

Another constraint we have is that having to make multiple passes over the data stream (like you'd have to do to inspect past the first byte) will be costly.  We process trillions of messages a day and even a handful of nanoseconds makes a real difference.  The logic in `Decoder` and the code generated by `protoc-gen-fastmarshal` is constructed to do as little work as possible and to avoid allocations anywhere possible.

FWIW, I'm not saying the use case is invalid.  It's just already covered by `protopack`.

Re-quoting from `README.md`
> Our intent is not to fully recreate the Protocol Buffers runtime.  Instead, `csproto` is built to determine which existing runtime is the "correct" one for a given message and to delegate to that implementation.

If you submit a PR I'll be glad to review it, but I won't be making this change.
Contraints:
- cannot change the signature of `Unmarshal()`
- works for code that's currently using Gogo Protobuf (another core requirement for us)
- does not negatively impact current benchmarks

**Comment by 89z** [comment] 2022-05-23 19:42
> The signature of `Unmarshal([]byte, interface{}) error` is intentionally and specifically set up to mirror `proto.Unmarshal()` from all 3 underlying runtime implementations. Changing that is unacceptable as it violates the primary reason this library exists, which is to be a shim between consumer code and the 3 runtimes.

Thats why I said "something like". If you don't or cant use that name, you could use something else, like

~~~go
func UnmarshalMonkey(b []byte, useMessage bool) (Message, error)
~~~

or whatever name you like.

> Another constraint we have is that having to make multiple passes over the data stream (like you'd have to do to inspect past the first byte) will be costly. We process trillions of messages a day and even a handful of nanoseconds makes a real difference. The logic in `Decoder` and the code generated by `protoc-gen-fastmarshal` is constructed to do as little work as possible and to avoid allocations anywhere possible.

The use case I am describing, in this current comment, and every single comment since the start, is not one of performance. If it was, then the issue would never be posted in the first place. If people want best speed, they use schema. If you don't have schema, you cannot get be speed, but you can still have a slower implementation of something.

> FWIW, I'm not saying the use case is invalid. It's just already covered by `protopack`.

No, its not. As a previously said, `protopack` doesn't give any control over the result. It makes a guess, and if user doesn't have a schema, they have to accept the result as is, even if a simple boolean switch could improve the result in some cases.

**Comment by dylan-bourque** [comment] 2022-05-23 19:59
I was just stating what I consider minimal constraints for adding something like this, which are 100% compatibility with Gogo/Google and cannot impact perf.  At the end of the day, though, I think I fall in the same camp as Joe and Damien on the other issue.

In my opinion, unmarshaling binary encoded Protobuf data without knowing the target types is a small use case and reworking `Decoder` to support look-ahead parsing for determining whether or not the next bytes contains a string or an embedded message would be a net loss.

Closing this for now, but feel free to re-open it later if you have a PR to submit.

**Closed by dylan-bourque** 2022-05-23 19:59 UTC
Labels: question

**Comment by 89z** [comment] 2022-05-23 21:59
Thanks for the feedback. I thought about this some more, and maybe you don't need an option after all. You could just add both types under the same key, something like this:

~~~go
type Message map[int]any

type String struct {
   Raw string
   Message
}
~~~

I am going to try to work up an implementation

**Comment by 89z** [comment] 2022-05-24 18:19
I think I have settled on something like this:

~~~go
package protobuf
import "google.golang.org/protobuf/encoding/protowire"

type Message map[protowire.Number]any

type Bytes struct {
   Raw []byte
   Message
}
~~~

I had to change from the previous example, as you can have bytes that appear as a string, but are in fact just some random bytes.
